"""Unit tests for AIActComplianceChecker — @pytest.mark.unit"""
import pytest
from pathlib import Path

from agenticqa.compliance.ai_act import (
    AIActFinding,
    AIActComplianceChecker,
    ConformityEvidence,
)


def make_checker() -> AIActComplianceChecker:
    return AIActComplianceChecker()


def write(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Risk classification
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestRiskClassification:
    def test_classify_high_risk_employment(self, tmp_path):
        write(tmp_path / "README.md",
              "# HireBot\nAI-powered hiring and recruitment platform for HR teams.\n")
        ev = make_checker().check(str(tmp_path))
        assert ev.risk_category == "high_risk"
        assert "employment" in ev.annex_iii_match

    def test_classify_high_risk_legal(self, tmp_path):
        write(tmp_path / "README.md",
              "# LegalAssist\nAI legal analysis and contract review for law firms.\n")
        ev = make_checker().check(str(tmp_path))
        assert ev.risk_category == "high_risk"
        assert "legal" in ev.annex_iii_match

    def test_classify_minimal_risk_generic(self, tmp_path):
        write(tmp_path / "README.md",
              "# MyApp\nA simple to-do list application with reminders.\n")
        ev = make_checker().check(str(tmp_path))
        assert ev.risk_category == "minimal_risk"
        assert ev.annex_iii_match == []

    def test_classify_limited_risk_chatbot(self, tmp_path):
        write(tmp_path / "README.md",
              "# ChatWidget\nA chatbot for customer support automation.\n")
        ev = make_checker().check(str(tmp_path))
        assert ev.risk_category == "limited_risk"


# ---------------------------------------------------------------------------
# Art. 9 — Risk management
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestArt9:
    def test_art9_missing_flagged(self, tmp_path):
        write(tmp_path / "app.py", "def run(): pass\n")
        ev = make_checker().check(str(tmp_path))
        art9 = [f for f in ev.findings if f.article == "Art.9"]
        assert len(art9) == 1
        assert art9[0].status == "missing"
        assert art9[0].severity == "critical"

    def test_art9_present_risk_doc(self, tmp_path):
        write(tmp_path / "RISK_MANAGEMENT.md",
              "# Risk Management\n## Identified Risks\n- Model hallucination\n")
        ev = make_checker().check(str(tmp_path))
        art9 = [f for f in ev.findings if f.article == "Art.9"]
        assert len(art9) == 1
        assert art9[0].status == "present"

    def test_art9_partial_code_pattern(self, tmp_path):
        write(tmp_path / "agent.py",
              "def handle_error():\n    risk_assessment = evaluate_risk()\n    return fallback_handler()\n")
        ev = make_checker().check(str(tmp_path))
        art9 = [f for f in ev.findings if f.article == "Art.9"]
        assert len(art9) == 1
        assert art9[0].status in ("partial", "present")


# ---------------------------------------------------------------------------
# Art. 13 — Transparency
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestArt13:
    def test_art13_disclosure_in_tsx(self, tmp_path):
        write(tmp_path / "components" / "Answer.tsx",
              '<p>AI-generated response</p>\n<span>Powered by AI</span>\n')
        ev = make_checker().check(str(tmp_path))
        art13 = [f for f in ev.findings if f.article == "Art.13"]
        assert len(art13) == 1
        assert art13[0].status == "present"

    def test_art13_missing_disclosure(self, tmp_path):
        write(tmp_path / "app.ts",
              'const response = await openai.chat.completions.create({model: "gpt-4o"});\n')
        ev = make_checker().check(str(tmp_path))
        art13 = [f for f in ev.findings if f.article == "Art.13"]
        assert len(art13) == 1
        assert art13[0].status == "missing"
        assert art13[0].severity == "high"

    def test_art13_partial_in_docs(self, tmp_path):
        write(tmp_path / "ARCHITECTURE.md",
              "# Architecture\nResponses are AI-generated by Claude.\n")
        ev = make_checker().check(str(tmp_path))
        art13 = [f for f in ev.findings if f.article == "Art.13"]
        assert art13[0].status in ("partial", "present")


# ---------------------------------------------------------------------------
# Art. 14 — Human oversight
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestArt14:
    def test_art14_oversight_present(self, tmp_path):
        write(tmp_path / "workflow.py",
              "if require_human_review(decision):\n    escalate_to_human(decision)\n")
        ev = make_checker().check(str(tmp_path))
        art14 = [f for f in ev.findings if f.article == "Art.14"]
        assert len(art14) == 1
        assert art14[0].status == "present"

    def test_art14_missing(self, tmp_path):
        write(tmp_path / "app.py", "def decide(x): return x > 0.5\n")
        ev = make_checker().check(str(tmp_path))
        art14 = [f for f in ev.findings if f.article == "Art.14"]
        assert len(art14) == 1
        assert art14[0].status == "missing"
        assert art14[0].severity == "high"


# ---------------------------------------------------------------------------
# Art. 22 — Automated decisions
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestArt22:
    def test_art22_decision_without_override(self, tmp_path):
        write(tmp_path / "scorer.py",
              "approved = response\nfail = result\n")
        ev = make_checker().check(str(tmp_path))
        art22 = [f for f in ev.findings if f.article == "Art.22"]
        assert len(art22) == 1
        assert art22[0].status == "missing"
        assert art22[0].severity == "critical"

    def test_art22_decision_with_override(self, tmp_path):
        write(tmp_path / "scorer.py",
              "approved = response\nif human_override():\n    approved = manual_review()\n")
        ev = make_checker().check(str(tmp_path))
        art22 = [f for f in ev.findings if f.article == "Art.22"]
        assert art22[0].status == "present"

    def test_art22_no_decision_is_present(self, tmp_path):
        write(tmp_path / "util.py", "def add(a, b):\n    return a + b\n")
        ev = make_checker().check(str(tmp_path))
        art22 = [f for f in ev.findings if f.article == "Art.22"]
        assert art22[0].status == "present"


# ---------------------------------------------------------------------------
# Conformity score
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestConformityScore:
    def test_all_present_score_one(self):
        checker = make_checker()
        findings = [
            AIActFinding("Art.9", "req", "present", "medium", "file.md", "tip"),
            AIActFinding("Art.13", "req", "present", "medium", "file.tsx", "tip"),
            AIActFinding("Art.14", "req", "present", "medium", "file.py", "tip"),
            AIActFinding("Art.22", "req", "present", "medium", "file.py", "tip"),
        ]
        assert checker._conformity_score(findings) == 1.0

    def test_all_missing_score_zero(self):
        checker = make_checker()
        findings = [
            AIActFinding("Art.9", "req", "missing", "critical", "not found", "tip"),
            AIActFinding("Art.13", "req", "missing", "high", "not found", "tip"),
        ]
        assert checker._conformity_score(findings) == 0.0

    def test_mixed_score(self):
        checker = make_checker()
        findings = [
            AIActFinding("Art.9", "req", "present", "medium", "f", "tip"),   # 1.0
            AIActFinding("Art.13", "req", "missing", "high", "f", "tip"),    # 0.0
        ]
        assert abs(checker._conformity_score(findings) - 0.5) < 0.01
