"""
Pydantic validation schemas for agent inputs/outputs.
Ensures agent-generated code and test cases conform to expected structures.
"""

from pydantic import BaseModel, Field, validator
from typing import List, Optional, Dict, Any
from enum import Enum


class TestType(str, Enum):
    """Supported test types generated by agents"""
    JEST = "jest"
    PLAYWRIGHT = "playwright"
    CYPRESS = "cypress"
    VITEST = "vitest"
    PA11Y = "pa11y"


class TestCase(BaseModel):
    """Schema for a single test case"""
    name: str = Field(..., min_length=1, max_length=200)
    description: str = Field(..., min_length=1, max_length=1000)
    test_type: TestType
    code: str = Field(..., min_length=10)
    assertions: List[str] = Field(..., min_items=1)
    
    @validator('code')
    def validate_code(cls, v):
        if not isinstance(v, str) or len(v.strip()) == 0:
            raise ValueError('Code cannot be empty')
        return v


class AgentOutput(BaseModel):
    """Schema for agent output validation"""
    status: str = Field(..., pattern="^(success|partial|failed)$")
    tests_generated: int = Field(..., ge=0, le=1000)
    issues_found: int = Field(..., ge=0)
    test_cases: List[TestCase] = Field(default=[])
    errors: List[str] = Field(default=[])
    metadata: Optional[Dict[str, Any]] = None


class ComplianceIssue(BaseModel):
    """Schema for compliance/security issues"""
    severity: str = Field(..., pattern="^(critical|high|medium|low)$")
    type: str
    description: str
    location: Optional[str] = None
    recommendation: str
    cwe_id: Optional[str] = None


class SecurityScanResult(BaseModel):
    """Schema for security scan results"""
    scan_type: str  # 'semgrep', 'npm-audit', 'trivy'
    timestamp: str
    total_issues: int
    issues: List[ComplianceIssue] = Field(default=[])
    passed: bool


# Example usage for agent validation
if __name__ == "__main__":
    # Validate agent output
    agent_output = AgentOutput(
        status="success",
        tests_generated=5,
        issues_found=2,
        test_cases=[
            TestCase(
                name="Login validation",
                description="Test login with valid credentials",
                test_type=TestType.JEST,
                code="describe('login', () => { it('should succeed with valid credentials', () => { expect(login('user', 'pass')).toBe(true); }); });",
                assertions=["login returns true", "no errors thrown"]
            )
        ]
    )
    
    print("✓ Agent output validated:", agent_output.dict())
