#!/usr/bin/env python3
"""
PR Risk Pre-flight Comment

Runs PRRiskScorer against the current PR (author + changed files + diff)
and posts the result as a GitHub PR comment *before* CI agents run.

This gives reviewers instant visibility into predicted risk without
waiting for the full CI pipeline to complete.

Usage (in CI on pull_request events):
    python post_pr_risk_comment.py \
        --base-ref origin/main \
        --author-email "${{ github.event.pull_request.user.login }}@users.noreply.github.com" \
        --repo-path . \
        --pr-number "${{ github.event.pull_request.number }}"
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent / "src"))

# Allowed characters in a git ref: alphanumeric, /, -, _, .
_SAFE_REF = re.compile(r"^[\w./\-~^@]+$")


def _validate_ref(ref: str) -> str:
    """Reject refs that contain shell-unsafe characters."""
    if not _SAFE_REF.match(ref):
        raise ValueError(f"Unsafe git ref rejected: {ref!r}")
    return ref


def _git(args: list[str], cwd: str = ".") -> str:
    result = subprocess.run(
        ["git"] + args, cwd=cwd, capture_output=True, text=True
    )
    return result.stdout.strip()


def _changed_files(base_ref: str, repo_path: str) -> list[str]:
    ref = _validate_ref(base_ref)
    output = _git(["diff", "--name-only", ref, "HEAD"], cwd=repo_path)
    return [f for f in output.splitlines() if f.strip()]


def _diff_text(base_ref: str, repo_path: str, max_bytes: int = 200_000) -> str:
    ref = _validate_ref(base_ref)
    output = _git(["diff", ref, "HEAD"], cwd=repo_path)
    return output[:max_bytes]


def _format_comment(report) -> str:
    icon = {"LOW RISK": "🟢", "MEDIUM RISK": "🟡", "HIGH RISK": "🔴"}.get(
        report.recommendation, "⚪"
    )
    lines = [
        f"## {icon} AgenticQA Pre-flight Risk Score: {report.risk_score:.0f}/100 — {report.recommendation}",
        "",
        "| Signal | Value |",
        "|--------|-------|",
        f"| Author fix-rate | {f'{report.author_fix_rate:.0%}' if report.author_fix_rate is not None else 'No history'} |",
        f"| Repo quality trend | {report.trend} |",
        f"| Unfixable rules in org memory | {len(report.unfixable_rules_hit)} |",
    ]

    if report.predicted_violations:
        lines += ["", "**Predicted violations:**"]
        for v in report.predicted_violations:
            lines.append(f"- `{v}`")

    if report.reasoning:
        lines += ["", "**Reasoning:**"]
        for r in report.reasoning:
            lines.append(f"- {r}")

    lines += [
        "",
        "<sub>Generated by [AgenticQA](https://github.com/nhomyk/AgenticQA) "
        "PR Risk Pre-flight Scorer · scores update on each push</sub>",
    ]
    return "\n".join(lines)


def _post_github_comment(repo: str, pr_number: str, body: str, token: str) -> bool:
    """
    Post a PR comment via GitHub REST API.
    Returns True on success, False on failure.
    Uses urllib (no subprocess) to avoid shell-exec risk.
    """
    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    payload = json.dumps({"body": body}).encode("utf-8")
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "Content-Type": "application/json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    try:
        req = urllib.request.Request(url, data=payload, headers=headers, method="POST")
        with urllib.request.urlopen(req, timeout=15) as resp:
            return resp.status in (200, 201)
    except (urllib.error.URLError, urllib.error.HTTPError) as exc:
        print(f"Warning: GitHub API call failed — {exc}", file=sys.stderr)
        return False


def main() -> int:
    parser = argparse.ArgumentParser(description="Post PR risk pre-flight comment")
    parser.add_argument("--base-ref", default="origin/main")
    parser.add_argument("--author-email", default="")
    parser.add_argument("--repo-path", default=".")
    parser.add_argument("--pr-number", default="")
    parser.add_argument("--github-repo", default=os.environ.get("GITHUB_REPOSITORY", ""))
    parser.add_argument("--dry-run", action="store_true",
                        help="Print comment without posting to GitHub")
    args = parser.parse_args()

    from agenticqa.scoring.pr_risk_scorer import PRRiskScorer

    changed = _changed_files(args.base_ref, args.repo_path)
    diff = _diff_text(args.base_ref, args.repo_path)

    report = PRRiskScorer().score(
        author_email=args.author_email,
        changed_files=changed,
        diff_lines=diff,
        repo_path=args.repo_path,
    )

    comment = _format_comment(report)

    if args.dry_run or not args.pr_number:
        print(comment)
        return 0

    token = os.environ.get("GITHUB_TOKEN", "")
    if not token:
        print("Warning: GITHUB_TOKEN not set — skipping comment post", file=sys.stderr)
        print(comment)
        return 0

    success = _post_github_comment(args.github_repo, args.pr_number, comment, token)
    if success:
        print(f"Posted risk pre-flight comment on PR #{args.pr_number} "
              f"— {report.recommendation} ({report.risk_score:.0f}/100)")
        return 0

    print("Failed to post GitHub comment", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
