#!/usr/bin/env python3
"""
Discover and execute custom agents from .agenticqa/custom_agents/*.py.

Each agent file must expose a function named `run(context: dict) -> dict`.
Sandboxed agents generated by AgentFactory already have this signature.
Results are ingested as artifacts for learning.

Security: every agent file is AST-scanned before being loaded. Files that
contain dangerous patterns (eval/exec/subprocess imports, governance-module
imports, cloud-metadata IPs, etc.) are blocked unless --no-scan is passed.

Usage:
    python run_custom_agents.py [--context-json path/to/context.json]
    python run_custom_agents.py --list
    python run_custom_agents.py --run-id $GITHUB_RUN_ID
    python run_custom_agents.py --no-scan   # emergency bypass (logs warning)
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import os
import sys
import time
import traceback
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

sys.path.insert(0, str(Path(__file__).parent / "src"))

try:
    from agenticqa.security.agent_skill_scanner import AgentSkillScanner, SkillScanResult
except ImportError:
    from src.agenticqa.security.agent_skill_scanner import AgentSkillScanner, SkillScanResult  # type: ignore

_scanner = AgentSkillScanner()

CUSTOM_AGENTS_DIR = Path(__file__).parent / ".agenticqa" / "custom_agents"
DEFAULT_CONTEXT: Dict[str, Any] = {
    "repo_path": ".",
    "run_id": os.getenv("GITHUB_RUN_ID", "local"),
    "ref": os.getenv("GITHUB_REF", "local"),
    "sha": os.getenv("GITHUB_SHA", ""),
}


# ── Discovery ─────────────────────────────────────────────────────────────────

def discover_agents(agents_dir: Path = CUSTOM_AGENTS_DIR) -> List[Path]:
    """Return all .py files in the custom agents directory, sorted by name."""
    if not agents_dir.exists():
        return []
    return sorted(agents_dir.glob("*.py"))


# ── Security pre-scan ─────────────────────────────────────────────────────────

def pre_scan_agent(
    agent_path: Path,
    scanner: AgentSkillScanner = None,
) -> Tuple[bool, "SkillScanResult"]:
    """
    AST-scan an agent file before loading it.

    Returns (is_safe, scan_result).  Callers should refuse to load the module
    when is_safe is False.
    """
    sc = scanner or _scanner
    result = sc.scan(agent_path)
    if not result.is_safe:
        print(f"  [BLOCKED] {agent_path.name} — security scan failed:")
        for f in result.findings:
            print(f"    {f.severity.upper()} {f.attack_type} line {f.lineno}: {f.detail}")
        if result.parse_error:
            print(f"    PARSE ERROR: {result.parse_error}")
    return result.is_safe, result


# ── Loading ───────────────────────────────────────────────────────────────────

def load_agent_module(agent_path: Path):
    """
    Dynamically load a custom agent .py file as a module.
    Returns the loaded module, or None if import fails.
    """
    spec = importlib.util.spec_from_file_location(agent_path.stem, agent_path)
    if spec is None or spec.loader is None:
        return None
    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)
        return module
    except Exception as exc:
        print(f"  WARN: Failed to load {agent_path.name}: {exc}")
        return None


# ── Execution ─────────────────────────────────────────────────────────────────

def run_agent(
    agent_path: Path,
    context: Dict[str, Any],
    skip_scan: bool = False,
) -> Dict[str, Any]:
    """
    Execute a single custom agent.

    Expects the module to expose `def run(context: dict) -> dict`.
    Non-sandboxed agents that expose `invoke()` instead are skipped with a warning
    (v1 limitation — full invoke() support is a planned extension).

    Returns a result dict with keys: agent_name, status, output, error, duration_ms.
    When the pre-scan blocks the agent, status is "blocked" instead of "error".
    """
    result: Dict[str, Any] = {
        "agent_name": agent_path.stem,
        "agent_file": str(agent_path),
        "status": "error",
        "output": {},
        "error": None,
        "duration_ms": 0,
    }

    # ── Security pre-scan ────────────────────────────────────────────────────
    if not skip_scan:
        safe, scan_result = pre_scan_agent(agent_path)
        if not safe:
            result["status"] = "blocked"
            result["error"] = (
                f"Pre-load security scan blocked agent. "
                f"Findings: {[f.detail for f in scan_result.findings]}"
            )
            result["scan_findings"] = scan_result.to_dict()
            return result

    module = load_agent_module(agent_path)
    if module is None:
        result["error"] = "Failed to import module"
        return result

    if not hasattr(module, "run"):
        if hasattr(module, "invoke"):
            result["error"] = (
                "Module exposes invoke() but not run() — "
                "non-sandboxed invoke() agents are not yet supported in CI runner"
            )
        else:
            result["error"] = "Module missing required run(context) function"
        return result

    start = time.time()
    try:
        output = module.run(context)
        result["status"] = "success"
        result["output"] = output if isinstance(output, dict) else {"result": output}
    except Exception:
        result["error"] = traceback.format_exc()[-2000:]  # cap at 2000 chars
    finally:
        result["duration_ms"] = round((time.time() - start) * 1000)

    return result


# ── Artifact ingestion ────────────────────────────────────────────────────────

def ingest_result(result: Dict[str, Any], run_id: str) -> None:
    """Store result in the artifact store for learning."""
    try:
        from data_store.artifact_store import TestArtifactStore
        store_path = os.getenv("AGENTICQA_ARTIFACT_STORE", ".test-artifact-store")
        store = TestArtifactStore(store_path)
        store.store_artifact(
            artifact_data={
                "artifact_type": "custom_agent_execution",
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "run_id": run_id,
                **result,
            },
            artifact_type="custom_agent_execution",
            source=result["agent_name"],
            tags=["custom_agent", result["status"]],
        )
    except Exception as exc:
        print(f"  WARN: Artifact ingestion failed for {result['agent_name']}: {exc}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Run custom agents from .agenticqa/custom_agents/"
    )
    parser.add_argument(
        "--context-json", help="Path to JSON file with execution context"
    )
    parser.add_argument(
        "--list", action="store_true", help="List discovered agents and exit"
    )
    parser.add_argument(
        "--run-id", default=os.getenv("GITHUB_RUN_ID", "local"),
        help="CI run ID for artifact tracking"
    )
    parser.add_argument(
        "--agents-dir", default=str(CUSTOM_AGENTS_DIR),
        help="Directory containing custom agent .py files"
    )
    parser.add_argument(
        "--no-scan", action="store_true",
        help="SECURITY WARNING: bypass pre-load AST scan (emergency use only)"
    )
    args = parser.parse_args()

    agents_dir = Path(args.agents_dir)
    agents = discover_agents(agents_dir)

    if args.list:
        print(f"Custom agents in {agents_dir}:")
        if agents:
            for a in agents:
                print(f"  - {a.name}")
        else:
            print("  (none found)")
        return 0

    if not agents:
        print(f"No custom agents found in {agents_dir}")
        print("Use 'POST /api/agent-factory/from-prompt' to create agents.")
        return 0

    # Build execution context
    context: Dict[str, Any] = dict(DEFAULT_CONTEXT)
    context["run_id"] = args.run_id
    if args.context_json:
        try:
            with open(args.context_json) as f:
                context.update(json.load(f))
        except Exception as exc:
            print(f"WARN: Could not load context JSON: {exc}")

    if args.no_scan:
        print(
            "\n*** SECURITY WARNING: --no-scan bypasses pre-load AST scanning. "
            "Only use in controlled environments with trusted agent files. ***\n"
        )

    print(f"Custom Agent Runner — {len(agents)} agent(s) discovered")
    print("=" * 60)

    results = []
    for agent_path in agents:
        print(f"\nRunning: {agent_path.name}")
        result = run_agent(agent_path, context, skip_scan=args.no_scan)
        results.append(result)

        status_icon = "OK  " if result["status"] == "success" else "FAIL"
        print(f"  [{status_icon}] {result['agent_name']} ({result['duration_ms']}ms)")
        if result["error"]:
            # Show first 200 chars of error inline; full error is in the result JSON
            print(f"  Error: {result['error'][:200]}")

        ingest_result(result, args.run_id)

    # Summary
    succeeded = sum(1 for r in results if r["status"] == "success")
    failed = len(results) - succeeded
    print(f"\nSummary: {succeeded}/{len(results)} agents succeeded, {failed} failed")

    # Write results file for CI artifact upload
    results_path = Path("custom-agents-output.json")
    results_path.write_text(json.dumps(
        {
            "run_id": args.run_id,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "agent_count": len(results),
            "succeeded": succeeded,
            "failed": failed,
            "results": results,
        },
        indent=2,
    ))
    print(f"Results written to {results_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
