#!/usr/bin/env python3
"""
Discover and execute custom agents from .agenticqa/custom_agents/*.py.

Each agent file must expose a function named `run(context: dict) -> dict`.
Sandboxed agents generated by AgentFactory already have this signature.
Results are ingested as artifacts for learning.

Usage:
    python run_custom_agents.py [--context-json path/to/context.json]
    python run_custom_agents.py --list
    python run_custom_agents.py --run-id $GITHUB_RUN_ID
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import os
import sys
import time
import traceback
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

sys.path.insert(0, str(Path(__file__).parent / "src"))

CUSTOM_AGENTS_DIR = Path(__file__).parent / ".agenticqa" / "custom_agents"
DEFAULT_CONTEXT: Dict[str, Any] = {
    "repo_path": ".",
    "run_id": os.getenv("GITHUB_RUN_ID", "local"),
    "ref": os.getenv("GITHUB_REF", "local"),
    "sha": os.getenv("GITHUB_SHA", ""),
}


# ── Discovery ─────────────────────────────────────────────────────────────────

def discover_agents(agents_dir: Path = CUSTOM_AGENTS_DIR) -> List[Path]:
    """Return all .py files in the custom agents directory, sorted by name."""
    if not agents_dir.exists():
        return []
    return sorted(agents_dir.glob("*.py"))


# ── Loading ───────────────────────────────────────────────────────────────────

def load_agent_module(agent_path: Path):
    """
    Dynamically load a custom agent .py file as a module.
    Returns the loaded module, or None if import fails.
    """
    spec = importlib.util.spec_from_file_location(agent_path.stem, agent_path)
    if spec is None or spec.loader is None:
        return None
    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)
        return module
    except Exception as exc:
        print(f"  WARN: Failed to load {agent_path.name}: {exc}")
        return None


# ── Execution ─────────────────────────────────────────────────────────────────

def run_agent(agent_path: Path, context: Dict[str, Any]) -> Dict[str, Any]:
    """
    Execute a single custom agent.

    Expects the module to expose `def run(context: dict) -> dict`.
    Non-sandboxed agents that expose `invoke()` instead are skipped with a warning
    (v1 limitation — full invoke() support is a planned extension).

    Returns a result dict with keys: agent_name, status, output, error, duration_ms.
    """
    result: Dict[str, Any] = {
        "agent_name": agent_path.stem,
        "agent_file": str(agent_path),
        "status": "error",
        "output": {},
        "error": None,
        "duration_ms": 0,
    }

    module = load_agent_module(agent_path)
    if module is None:
        result["error"] = "Failed to import module"
        return result

    if not hasattr(module, "run"):
        if hasattr(module, "invoke"):
            result["error"] = (
                "Module exposes invoke() but not run() — "
                "non-sandboxed invoke() agents are not yet supported in CI runner"
            )
        else:
            result["error"] = "Module missing required run(context) function"
        return result

    start = time.time()
    try:
        output = module.run(context)
        result["status"] = "success"
        result["output"] = output if isinstance(output, dict) else {"result": output}
    except Exception:
        result["error"] = traceback.format_exc()[-2000:]  # cap at 2000 chars
    finally:
        result["duration_ms"] = round((time.time() - start) * 1000)

    return result


# ── Artifact ingestion ────────────────────────────────────────────────────────

def ingest_result(result: Dict[str, Any], run_id: str) -> None:
    """Store result in the artifact store for learning."""
    try:
        from data_store.artifact_store import TestArtifactStore
        store_path = os.getenv("AGENTICQA_ARTIFACT_STORE", ".test-artifact-store")
        store = TestArtifactStore(store_path)
        store.store_artifact(
            artifact_data={
                "artifact_type": "custom_agent_execution",
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "run_id": run_id,
                **result,
            },
            artifact_type="custom_agent_execution",
            source=result["agent_name"],
            tags=["custom_agent", result["status"]],
        )
    except Exception as exc:
        print(f"  WARN: Artifact ingestion failed for {result['agent_name']}: {exc}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Run custom agents from .agenticqa/custom_agents/"
    )
    parser.add_argument(
        "--context-json", help="Path to JSON file with execution context"
    )
    parser.add_argument(
        "--list", action="store_true", help="List discovered agents and exit"
    )
    parser.add_argument(
        "--run-id", default=os.getenv("GITHUB_RUN_ID", "local"),
        help="CI run ID for artifact tracking"
    )
    parser.add_argument(
        "--agents-dir", default=str(CUSTOM_AGENTS_DIR),
        help="Directory containing custom agent .py files"
    )
    args = parser.parse_args()

    agents_dir = Path(args.agents_dir)
    agents = discover_agents(agents_dir)

    if args.list:
        print(f"Custom agents in {agents_dir}:")
        if agents:
            for a in agents:
                print(f"  - {a.name}")
        else:
            print("  (none found)")
        return 0

    if not agents:
        print(f"No custom agents found in {agents_dir}")
        print("Use 'POST /api/agent-factory/from-prompt' to create agents.")
        return 0

    # Build execution context
    context: Dict[str, Any] = dict(DEFAULT_CONTEXT)
    context["run_id"] = args.run_id
    if args.context_json:
        try:
            with open(args.context_json) as f:
                context.update(json.load(f))
        except Exception as exc:
            print(f"WARN: Could not load context JSON: {exc}")

    print(f"Custom Agent Runner — {len(agents)} agent(s) discovered")
    print("=" * 60)

    results = []
    for agent_path in agents:
        print(f"\nRunning: {agent_path.name}")
        result = run_agent(agent_path, context)
        results.append(result)

        status_icon = "OK  " if result["status"] == "success" else "FAIL"
        print(f"  [{status_icon}] {result['agent_name']} ({result['duration_ms']}ms)")
        if result["error"]:
            # Show first 200 chars of error inline; full error is in the result JSON
            print(f"  Error: {result['error'][:200]}")

        ingest_result(result, args.run_id)

    # Summary
    succeeded = sum(1 for r in results if r["status"] == "success")
    failed = len(results) - succeeded
    print(f"\nSummary: {succeeded}/{len(results)} agents succeeded, {failed} failed")

    # Write results file for CI artifact upload
    results_path = Path("custom-agents-output.json")
    results_path.write_text(json.dumps(
        {
            "run_id": args.run_id,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "agent_count": len(results),
            "succeeded": succeeded,
            "failed": failed,
            "results": results,
        },
        indent=2,
    ))
    print(f"Results written to {results_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
