/**
 * UI Tests for settings.html
 * Auto-generated by SDET UI Change Detector
 * 
 * Tests the "🔑 Manual GitHub Setup" UI fix
 * 
 * Coverage:
 * - Form field clearing on cancel
 * - Modal visibility state management
 * - Button functionality
 * - Scroll behavior
 * - Accessibility
 */

describe('settings - Manual GitHub Setup UI Fix', () => {
  beforeEach(() => {
    cy.visit('/settings.html');
  });

  describe('Manual GitHub Token Card - Show/Hide', () => {
    it('should initially hide the manual token card', () => {
      cy.get('#manualTokenCard').should('have.css', 'display', 'none');
    });

    it('should show manual token card when clicking Personal Access Token button', () => {
      cy.get('#manualTokenBtn').click();
      cy.get('#manualTokenCard').should('not.have.css', 'display', 'none');
      cy.get('#manualTokenCard').should('be.visible');
    });

    it('should scroll card into view when shown', () => {
      cy.get('#manualTokenBtn').click();
      cy.get('#manualTokenCard').then($card => {
        expect($card[0].scrollIntoView).toBeDefined();
      });
    });

    it('should focus on token input when card is shown', () => {
      cy.get('#manualTokenBtn').click();
      cy.get('#githubToken').should('be.focused');
    });
  });

  describe('Form Field Clearing on Cancel', () => {
    it('should clear GitHub token field when cancel is clicked', () => {
      // Show the card
      cy.get('#manualTokenBtn').click();
      
      // Enter a token value
      cy.get('#githubToken').type('ghp_test123456789');
      cy.get('#githubToken').should('have.value', 'ghp_test123456789');
      
      // Click cancel
      cy.contains('button', 'Cancel').click();
      
      // Verify card is hidden
      cy.get('#manualTokenCard').should('have.css', 'display', 'none');
      
      // Verify field is cleared (for next time card is shown)
      cy.get('#manualTokenBtn').click();
      cy.get('#githubToken').should('have.value', '');
    });

    it('should clear repository field when cancel is clicked', () => {
      cy.get('#manualTokenBtn').click();
      
      // Enter repository value
      cy.get('#githubRepo').type('username/repo');
      cy.get('#githubRepo').should('have.value', 'username/repo');
      
      // Click cancel
      cy.contains('button', 'Cancel').click();
      
      // Verify field is cleared for next time
      cy.get('#manualTokenBtn').click();
      cy.get('#githubRepo').should('have.value', '');
    });

    it('should clear both fields when cancel is clicked', () => {
      cy.get('#manualTokenBtn').click();
      
      // Fill both fields
      cy.get('#githubToken').type('ghp_test123456789');
      cy.get('#githubRepo').type('username/repo');
      
      // Click cancel
      cy.contains('button', 'Cancel').click();
      
      // Reopen and verify both are cleared
      cy.get('#manualTokenBtn').click();
      cy.get('#githubToken').should('have.value', '');
      cy.get('#githubRepo').should('have.value', '');
    });
  });

  describe('Button Interactions', () => {
    it('should have visible and enabled Save Token button', () => {
      cy.get('#manualTokenBtn').click();
      cy.contains('button', 'Save Token')
        .should('be.visible')
        .and('be.enabled');
    });

    it('should have visible and enabled Cancel button', () => {
      cy.get('#manualTokenBtn').click();
      cy.contains('button', 'Cancel')
        .should('be.visible')
        .and('be.enabled');
    });

    it('should have proper button types', () => {
      cy.get('#manualTokenBtn').click();
      cy.contains('button', 'Save Token')
        .should('have.attr', 'class')
        .and('include', 'btn');
      cy.contains('button', 'Cancel')
        .should('have.attr', 'class')
        .and('include', 'btn');
    });
  });

  describe('Form Interactions', () => {
    it('should allow entering GitHub token', () => {
      cy.get('#manualTokenBtn').click();
      
      cy.get('#githubToken')
        .type('ghp_1234567890abcdefghijklmnopqrstuv')
        .should('have.value', 'ghp_1234567890abcdefghijklmnopqrstuv');
    });

    it('should allow entering repository name', () => {
      cy.get('#manualTokenBtn').click();
      
      cy.get('#githubRepo')
        .type('username/repository')
        .should('have.value', 'username/repository');
    });

    it('should show token field as password type', () => {
      cy.get('#manualTokenBtn').click();
      
      cy.get('#githubToken')
        .should('have.attr', 'type', 'password');
    });

    it('should show placeholder text in token field', () => {
      cy.get('#manualTokenBtn').click();
      
      cy.get('#githubToken')
        .should('have.attr', 'placeholder');
    });
  });

  describe('Modal/Card Styling', () => {
    it('should have correct styling when visible', () => {
      cy.get('#manualTokenBtn').click();
      
      cy.get('#manualTokenCard')
        .should('have.class', 'card')
        .and('have.css', 'border-left', '4px solid rgb(102, 126, 234)');
    });

    it('should have heading describing manual setup', () => {
      cy.get('#manualTokenBtn').click();
      
      cy.get('#manualTokenCard')
        .find('h2')
        .should('contain', 'Manual GitHub Setup');
    });

    it('should have helpful instructions', () => {
      cy.get('#manualTokenBtn').click();
      
      cy.get('#manualTokenCard')
        .find('.instructions')
        .should('exist')
        .and('be.visible');
    });
  });

  describe('User Flow - Complete Scenario', () => {
    it('should support full manual token entry workflow', () => {
      // Click to show manual token setup
      cy.get('#manualTokenBtn').click();
      cy.get('#manualTokenCard').should('be.visible');
      
      // Fill in the form
      cy.get('#githubToken').type('ghp_testtoken123456789');
      cy.get('#githubRepo').type('testuser/testrepo');
      
      // Save (this would normally make API call)
      // cy.contains('button', 'Save Token').click();
      
      // For this test, just cancel
      cy.contains('button', 'Cancel').click();
      
      // Card should be hidden
      cy.get('#manualTokenCard').should('have.css', 'display', 'none');
      
      // Try again - should be fresh
      cy.get('#manualTokenBtn').click();
      cy.get('#githubToken').should('have.value', '');
      cy.get('#githubRepo').should('have.value', '');
    });

    it('should allow user to retry after canceling', () => {
      // First attempt
      cy.get('#manualTokenBtn').click();
      cy.get('#githubToken').type('wrong_token');
      cy.contains('button', 'Cancel').click();
      
      // Second attempt
      cy.get('#manualTokenBtn').click();
      cy.get('#githubToken').should('have.value', '');
      cy.get('#githubToken').type('correct_token');
      cy.get('#githubToken').should('have.value', 'correct_token');
    });
  });

  describe('Accessibility', () => {
    it('should have proper form labels', () => {
      cy.get('#manualTokenBtn').click();
      
      cy.get('#githubToken').should('have.attr', 'aria-label');
      cy.get('#githubRepo').should('have.attr', 'aria-label');
    });

    it('should have descriptive aria labels', () => {
      cy.get('#manualTokenBtn').click();
      
      cy.get('#githubToken')
        .should('have.attr', 'aria-label')
        .and('include', 'token');
      cy.get('#githubRepo')
        .should('have.attr', 'aria-label')
        .and('include', 'repository');
    });

    it('should support keyboard navigation', () => {
      cy.get('#manualTokenBtn').click();
      
      // Tab through fields
      cy.get('#githubToken').focus();
      cy.focused().should('have.id', 'githubToken');
      
      cy.get('#githubToken').tab();
      cy.focused().should('have.id', 'githubRepo');
    });

    it('should be compatible with screen readers', () => {
      cy.get('#manualTokenBtn').click();
      
      // Check for form help text
      cy.get('#manualTokenCard')
        .find('.form-help')
        .should('exist')
        .and('be.visible');
    });
  });

  describe('State Management', () => {
    it('should not persist form values between show/hide cycles', () => {
      // Show, fill, hide
      cy.get('#manualTokenBtn').click();
      cy.get('#githubToken').type('persist_test_token');
      cy.contains('button', 'Cancel').click();
      
      // Verify not visible
      cy.get('#manualTokenCard').should('have.css', 'display', 'none');
      
      // Show again
      cy.get('#manualTokenBtn').click();
      
      // Verify cleared
      cy.get('#githubToken').should('have.value', '');
    });

    it('should handle multiple show/hide cycles', () => {
      for (let i = 0; i < 3; i++) {
        cy.get('#manualTokenBtn').click();
        cy.get('#githubToken').should('have.value', '');
        cy.contains('button', 'Cancel').click();
      }
    });
  });
});
