"""Generic adapter — wraps any callable agent with a constitutional wrapper."""

from __future__ import annotations

from typing import Any, List, Optional

from agenticqa.factory.constitutional_wrapper import ConstitutionalWrapper

_GENERIC_TEMPLATE = '''"""
{agent_name} — governed agent ({framework})
Auto-generated by AgenticQA Agent Factory. Constitutional governance pre-wired.
"""

from agenticqa.factory import ConstitutionalWrapper


class {class_name}:
    """
    Governed {framework} agent: {agent_name}
    Capabilities: {capabilities}

    Usage:
        agent = {class_name}()
        result = agent.invoke({{"input": "your prompt here"}})
    """

    def __init__(self):
        self._governed = ConstitutionalWrapper(
            agent=self._run,
            agent_name="{agent_name}",
            framework="{framework}",
            capabilities={capabilities!r},
        )

    def _run(self, input: dict) -> dict:
        """Core agent logic — implement your {framework} agent here."""
        # TODO: replace with your {framework} implementation
        return {{"agent": "{agent_name}", "input": input, "output": "implement me"}}

    def invoke(self, input: dict, **kwargs) -> dict:
        return self._governed.invoke(input, **kwargs)

    def run(self, input: dict, **kwargs) -> dict:
        return self._governed.run(input, **kwargs)
'''


class GenericAdapter:
    """Adapter for any callable agent — no framework-specific hooks."""

    @staticmethod
    def wrap(agent: Any, agent_name: str, capabilities: Optional[List[str]] = None, framework: str = "generic") -> ConstitutionalWrapper:
        """Wrap any callable with constitutional governance."""
        return ConstitutionalWrapper(
            agent=agent,
            agent_name=agent_name,
            framework=framework,
            capabilities=capabilities or [],
        )

    @staticmethod
    def scaffold(agent_name: str, capabilities: List[str], framework: str = "custom") -> str:
        """Generate governed agent boilerplate for the given framework."""
        class_name = "".join(w.capitalize() for w in agent_name.replace("-", "_").split("_")) + "Agent"
        return _GENERIC_TEMPLATE.format(
            agent_name=agent_name,
            class_name=class_name,
            framework=framework,
            capabilities=capabilities,
        )
