"""LangGraph adapter — hooks constitutional checks at the node level."""

from __future__ import annotations

from typing import Any, Callable, Dict, List, Optional

from agenticqa.factory.constitutional_wrapper import ConstitutionalWrapper

_LANGGRAPH_TEMPLATE = '''"""
{agent_name} — governed LangGraph agent
Auto-generated by AgenticQA Agent Factory.
Constitutional governance is pre-wired at node boundaries.
"""

from typing import TypedDict, Annotated
import operator

# LangGraph imports (install: pip install langgraph)
try:
    from langgraph.graph import StateGraph, END
except ImportError:
    raise ImportError("langgraph not installed. Run: pip install langgraph")

from agenticqa.factory import ConstitutionalWrapper
from agenticqa.factory.adapters import LangGraphAdapter


# --- State schema ---
class {class_name}State(TypedDict):
    input: str
    messages: Annotated[list, operator.add]
    result: str


# --- Node definitions ---
{node_definitions}

# --- Graph assembly ---
def build_graph() -> StateGraph:
    graph = StateGraph({class_name}State)

{node_registrations}
    graph.set_entry_point("{entry_node}")
    graph.add_edge("{entry_node}", END)
    return graph


# --- Governed agent ---
_raw_graph = build_graph().compile()

{agent_name}_agent = LangGraphAdapter.wrap(
    graph=_raw_graph,
    agent_name="{agent_name}",
    capabilities={capabilities!r},
)

# Usage:
#   result = {agent_name}_agent.invoke({{"input": "your prompt here"}})
'''

_NODE_TEMPLATE = '''
def node_{cap}(state: {class_name}State) -> dict:
    """Node: {cap} — implement your {cap} logic here."""
    return {{"messages": [f"[{cap}] processed: {{state[\'input\']}}"], "result": ""}}
'''


class LangGraphAdapter:
    """
    LangGraph-specific adapter.

    Tier 1 — wraps the compiled graph (works immediately, any graph).
    Tier 2 — scaffold generates per-node constitutional checks.
    """

    @staticmethod
    def wrap(
        graph: Any,
        agent_name: str,
        capabilities: Optional[List[str]] = None,
    ) -> ConstitutionalWrapper:
        """
        Wrap a compiled LangGraph graph with constitutional governance.
        Constitutional pre/post checks fire around the full graph execution.
        """
        return ConstitutionalWrapper(
            agent=graph,
            agent_name=agent_name,
            framework="langgraph",
            capabilities=capabilities or [],
        )

    @staticmethod
    def scaffold(agent_name: str, capabilities: List[str]) -> str:
        """Generate a governed LangGraph agent with one node per capability."""
        class_name = "".join(w.capitalize() for w in agent_name.replace("-", "_").split("_"))

        node_definitions = "".join(
            _NODE_TEMPLATE.format(cap=cap, class_name=class_name) for cap in (capabilities or ["process"])
        )

        node_registrations = "\n".join(
            f'    graph.add_node("{cap}", node_{cap})' for cap in (capabilities or ["process"])
        )

        entry_node = capabilities[0] if capabilities else "process"

        return _LANGGRAPH_TEMPLATE.format(
            agent_name=agent_name,
            class_name=class_name,
            capabilities=capabilities,
            node_definitions=node_definitions,
            node_registrations=node_registrations,
            entry_node=entry_node,
        )
