"""
SandboxedAgentAdapter — wraps any agent script with subprocess isolation.

The agent must be a standalone Python script that:
  - reads its task as JSON from stdin
  - writes its result as JSON to stdout
  - exits 0 on success

The adapter enforces:
  1. Constitutional gate check (DENY/REQUIRE_APPROVAL/ALLOW) — before any subprocess launch
  2. Subprocess isolation — clean env, restricted cwd, hard timeout
  3. Output scanning — flags secrets, path traversal, injected shell commands
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from agenticqa.factory.constitutional_wrapper import ConstitutionalWrapper, ConstitutionalViolationError
from agenticqa.factory.sandbox.subprocess_runner import SubprocessRunner
from agenticqa.factory.sandbox.output_scanner import OutputScanner


class SandboxOutputFlaggedError(ConstitutionalViolationError):
    """Raised when the output scanner detects a danger pattern and block_on_flag=True."""


_SANDBOXED_TEMPLATE = '''\
"""
{agent_name} — sandboxed governed agent
Auto-generated by AgenticQA Agent Factory. Runs under subprocess isolation.

This script is launched as a subprocess by SandboxedAgentAdapter:
  - Input:  JSON from stdin
  - Output: JSON to stdout (exit 0 = success)

Capabilities: {capabilities}
"""

import json
import sys


def run(task: dict) -> dict:
    """
    Core agent logic — implement your agent here.
    Return a dict; it will be JSON-serialized to stdout.
    """
    # TODO: Replace with real implementation
    capabilities = {capabilities!r}
    return {{
        "agent": "{agent_name}",
        "status": "ok",
        "capabilities": capabilities,
        "input_keys": list(task.keys()),
        "output": "implement me",
    }}


if __name__ == "__main__":
    try:
        raw = sys.stdin.read()
        task = json.loads(raw) if raw.strip() else {{}}
        result = run(task)
        print(json.dumps(result))
        sys.exit(0)
    except Exception as exc:
        print(json.dumps({{"error": str(exc), "agent": "{agent_name}"}}), file=sys.stderr)
        sys.exit(1)
'''


class SandboxedAgentAdapter:
    """
    Adapter for running any autonomous agent in a subprocess sandbox.

    Use wrap() to govern an existing script.
    Use scaffold() to generate a governed standalone script template.
    """

    @staticmethod
    def wrap(
        script_path: str,
        agent_name: str,
        capabilities: Optional[List[str]] = None,
        allowed_dir: str = ".",
        timeout_s: int = 30,
        env_passthrough: Optional[List[str]] = None,
        block_on_flag: bool = True,
    ) -> ConstitutionalWrapper:
        """
        Wrap a standalone agent script with constitutional governance + subprocess sandbox.

        Args:
            script_path:    Path to the standalone Python agent script.
            agent_name:     Unique name (used in audit logs, constitutional gate context).
            capabilities:   Human-readable list of what this agent does.
            allowed_dir:    Subprocess cwd — the only directory the subprocess sees.
            timeout_s:      Hard timeout in seconds (default 30).
            env_passthrough: Env var names to pass into the subprocess (all others stripped).
            block_on_flag:  If True (default), raise on flagged output; if False, annotate only.
        """
        runner = SubprocessRunner(allowed_dir, timeout_s, env_passthrough)
        scanner = OutputScanner()

        def _sandboxed_invoke(input_payload: Dict[str, Any]) -> Dict[str, Any]:
            raw = runner.run(script_path, input_payload)
            scan = scanner.scan(raw)
            if block_on_flag and not scan["clean"]:
                raise SandboxOutputFlaggedError(
                    f"[{agent_name}] Output scanner flagged: {scan['flags']}"
                )
            raw["_scan"] = scan
            return raw

        return ConstitutionalWrapper(
            agent=_sandboxed_invoke,
            agent_name=agent_name,
            framework="sandboxed",
            capabilities=capabilities or [],
        )

    @staticmethod
    def scaffold(agent_name: str, capabilities: List[str]) -> str:
        """
        Generate a standalone Python script template for a sandboxed agent.

        The generated script reads JSON from stdin and writes JSON to stdout,
        ready to be wrapped by SandboxedAgentAdapter.wrap().
        """
        return _SANDBOXED_TEMPLATE.format(
            agent_name=agent_name,
            capabilities=capabilities,
        )
