"""
EU AI Act Compliance Layer for the ComplianceAgent.

Classifies repositories under Annex III (high-risk AI) and checks for
conformity evidence across the four most-critical articles:
  - Art. 9  — Risk management system
  - Art. 13 — Transparency and provision of information
  - Art. 14 — Human oversight
  - Art. 22 — Automated individual decision-making

Full enforcement August 2026. High-risk systems (employment, legal, credit,
education, critical infrastructure) face fines up to 30M EUR / 6% global turnover.

Subprocess-free: pure Python (re, pathlib). Mirrors LegalRiskScanner pattern.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple


# ---------------------------------------------------------------------------
# Annex III high-risk keyword mapping
# ---------------------------------------------------------------------------
_HIGH_RISK_KEYWORDS: Dict[str, List[str]] = {
    "employment": ["hiring", "recruitment", "cv", "resume", "employee", "termination",
                   "workforce", "talent", "hr", "payroll", "performance review"],
    "legal": ["lawyer", "legal", "court", "litigation", "contract", "compliance",
              "attorney", "counsel", "law firm", "paralegal", "eDiscovery"],
    "credit": ["loan", "credit", "financial", "mortgage", "scoring", "lending",
               "underwriting", "risk assessment", "creditworthiness"],
    "education": ["exam", "student", "grade", "assessment", "admission", "learning",
                  "educational", "tutoring", "school", "university"],
    "critical_infra": ["power", "water", "transport", "hospital", "emergency",
                       "grid", "energy", "infrastructure", "safety system"],
    "biometric": ["face recognition", "fingerprint", "biometric", "iris scan",
                  "voice recognition", "gait analysis"],
    "law_enforcement": ["police", "criminal", "fraud detection", "border control",
                        "surveillance", "predictive policing"],
}

_LIMITED_RISK_KEYWORDS = ["chatbot", "recommendation", "content generation",
                           "image synthesis", "translation"]

_SKIP_DIRS = {
    "node_modules", ".venv", "venv", "__pycache__",
    ".git", "dist", "build", ".next", "out",
}
_TEXT_EXTS = {".md", ".txt", ".rst", ".json", ".yaml", ".yml", ".py",
              ".ts", ".tsx", ".js", ".jsx", ".html"}

# ---------------------------------------------------------------------------
# Article check patterns
# ---------------------------------------------------------------------------

# Art. 9 — Risk management system
_ART9_DOCS = ["RISK_MANAGEMENT.md", "risk_management.md", "risk_assessment.md",
               "RISK_ASSESSMENT.md", "risk_register.md", "RISK_REGISTER.md",
               "security_policy.md", "SECURITY.md"]
_ART9_CODE_PATTERN = re.compile(
    r"(risk_assessment|risk_management|risk_register|fallback_handler|"
    r"error_recovery|circuit_breaker|graceful_degrad)",
    re.IGNORECASE,
)

# Art. 13 — Transparency disclosure
_ART13_PATTERNS = re.compile(
    r"(AI.?generated|artificial intelligence|automated|generated by (AI|Claude|GPT|LLM)|"
    r"this (response|answer|summary) (was |is )?(generated|produced) by|"
    r"ai_generated|isAiGenerated|powered by (AI|machine learning))",
    re.IGNORECASE,
)
_ART13_UI_EXTS = {".tsx", ".jsx", ".html", ".ts", ".js"}

# Art. 14 — Human oversight
_ART14_PATTERNS = re.compile(
    r"(require_human_review|human_in_the_loop|human_oversight|"
    r"approval_required|manual_review|human_approval|"
    r"escalate_to_human|override|audit_log|decision_log)",
    re.IGNORECASE,
)

# Art. 22 — Automated decisions
_ART22_DECISION_PATTERN = re.compile(
    r"(pass|fail|approved|rejected|denied|accepted|scored|ranked)\s*[=:]\s*"
    r"(llm_?output|response|completion|answer|result|prediction)",
    re.IGNORECASE,
)
_ART22_OVERRIDE_PATTERN = re.compile(
    r"(human_override|override_decision|manual_override|appeal|"
    r"require_human|human_review|reject_automated)",
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------

@dataclass
class AIActFinding:
    article: str        # "Art.9", "Art.13", "Art.14", "Art.22"
    requirement: str    # short human-readable requirement description
    status: str         # "present" | "missing" | "partial"
    severity: str       # "critical" | "high" | "medium"
    evidence: str       # file:line or "not found"
    remediation: str    # one-line fix instruction


@dataclass
class ConformityEvidence:
    risk_category: str               # "high_risk" | "limited_risk" | "minimal_risk"
    annex_iii_match: List[str]       # matched Annex III categories
    findings: List[AIActFinding]
    conformity_score: float          # 0.0–1.0
    scan_error: Optional[str] = None


# ---------------------------------------------------------------------------
# Checker
# ---------------------------------------------------------------------------

class AIActComplianceChecker:
    """
    Pure-Python EU AI Act conformity checker.

    Classifies the repository's risk tier under Annex III and checks
    for evidence of Art.9/13/14/22 requirements. Non-blocking; called
    from ComplianceAgent.execute() in a try/except block.
    """

    def check(self, repo_path: str = ".") -> ConformityEvidence:
        try:
            repo = Path(repo_path).resolve()
            risk_category, annex_match = self._classify_risk(repo)
            findings: List[AIActFinding] = []
            findings.extend(self._check_art9_risk_management(repo))
            findings.extend(self._check_art13_transparency(repo))
            findings.extend(self._check_art14_human_oversight(repo))
            findings.extend(self._check_art22_automated_decisions(repo))
            score = self._conformity_score(findings)
            return ConformityEvidence(
                risk_category=risk_category,
                annex_iii_match=annex_match,
                findings=findings,
                conformity_score=score,
            )
        except Exception as exc:
            return ConformityEvidence(
                risk_category="unknown",
                annex_iii_match=[],
                findings=[],
                conformity_score=0.0,
                scan_error=str(exc),
            )

    # ------------------------------------------------------------------
    # Risk classification
    # ------------------------------------------------------------------

    def _classify_risk(self, repo: Path) -> Tuple[str, List[str]]:
        """Scan descriptive files for Annex III keywords."""
        probe_texts: List[str] = []
        for fname in ["README.md", "readme.md", "README.rst", "package.json",
                      "pyproject.toml", "setup.py", "DESCRIPTION.md"]:
            fp = repo / fname
            if fp.exists():
                try:
                    probe_texts.append(fp.read_text(encoding="utf-8", errors="replace").lower())
                except OSError:
                    pass
        combined = " ".join(probe_texts)
        matched_categories: List[str] = []
        for category, keywords in _HIGH_RISK_KEYWORDS.items():
            if any(kw.lower() in combined for kw in keywords):
                matched_categories.append(category)
        if matched_categories:
            return "high_risk", matched_categories
        if any(kw.lower() in combined for kw in _LIMITED_RISK_KEYWORDS):
            return "limited_risk", []
        return "minimal_risk", []

    # ------------------------------------------------------------------
    # Article checks
    # ------------------------------------------------------------------

    def _check_art9_risk_management(self, repo: Path) -> List[AIActFinding]:
        # Check for risk management documentation
        for doc in _ART9_DOCS:
            if (repo / doc).exists():
                return [AIActFinding(
                    article="Art.9",
                    requirement="Risk management system documented",
                    status="present",
                    severity="medium",
                    evidence=doc,
                    remediation="Keep risk register updated with each model/data change.",
                )]
        # Check for code-level risk patterns
        for fpath in self._iter_text_files(repo):
            try:
                content = fpath.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            if _ART9_CODE_PATTERN.search(content):
                rel = str(fpath.relative_to(repo))
                return [AIActFinding(
                    article="Art.9",
                    requirement="Risk management system in code",
                    status="partial",
                    severity="high",
                    evidence=rel,
                    remediation="Add RISK_MANAGEMENT.md documenting identified risks, mitigations, and residual risk acceptance.",
                )]
        return [AIActFinding(
            article="Art.9",
            requirement="Risk management system (Art. 9 EU AI Act)",
            status="missing",
            severity="critical",
            evidence="not found",
            remediation="Create RISK_MANAGEMENT.md with risk register, mitigation measures, and residual risk sign-off.",
        )]

    def _check_art13_transparency(self, repo: Path) -> List[AIActFinding]:
        """Look for AI transparency disclosures in UI code or API responses."""
        for fpath in self._iter_text_files(repo, exts=_ART13_UI_EXTS):
            try:
                content = fpath.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            if _ART13_PATTERNS.search(content):
                rel = str(fpath.relative_to(repo))
                return [AIActFinding(
                    article="Art.13",
                    requirement="AI-generated output disclosed to users",
                    status="present",
                    severity="medium",
                    evidence=rel,
                    remediation="Ensure disclosure is visible on every AI-generated output, not only in some code paths.",
                )]
        # Check markdown docs for disclosure language
        for fpath in self._iter_text_files(repo, exts={".md", ".txt", ".html"}):
            try:
                content = fpath.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            if _ART13_PATTERNS.search(content):
                rel = str(fpath.relative_to(repo))
                return [AIActFinding(
                    article="Art.13",
                    requirement="AI disclosure in documentation",
                    status="partial",
                    severity="high",
                    evidence=rel,
                    remediation="Add runtime disclosure to every user-visible AI response, not only in docs.",
                )]
        return [AIActFinding(
            article="Art.13",
            requirement="Transparency — inform users they are interacting with AI (Art. 13)",
            status="missing",
            severity="high",
            evidence="not found",
            remediation="Add 'AI-generated' label to all outputs; expose ai_generated: true field in API responses.",
        )]

    def _check_art14_human_oversight(self, repo: Path) -> List[AIActFinding]:
        """Look for human review, override, or audit logging mechanisms."""
        for fpath in self._iter_text_files(repo):
            try:
                content = fpath.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            if _ART14_PATTERNS.search(content):
                rel = str(fpath.relative_to(repo))
                return [AIActFinding(
                    article="Art.14",
                    requirement="Human oversight mechanism present",
                    status="present",
                    severity="medium",
                    evidence=rel,
                    remediation="Ensure override/escalation path is reachable from every automated decision.",
                )]
        return [AIActFinding(
            article="Art.14",
            requirement="Human oversight — operators can monitor, intervene, override (Art. 14)",
            status="missing",
            severity="high",
            evidence="not found",
            remediation="Implement require_human_review() gate and audit_log for all consequential AI decisions.",
        )]

    def _check_art22_automated_decisions(self, repo: Path) -> List[AIActFinding]:
        """Detect LLM output used directly as a pass/fail decision without human override."""
        decision_files: List[str] = []
        override_found = False
        for fpath in self._iter_text_files(repo):
            try:
                content = fpath.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            rel = str(fpath.relative_to(repo))
            if _ART22_DECISION_PATTERN.search(content):
                decision_files.append(rel)
            if _ART22_OVERRIDE_PATTERN.search(content):
                override_found = True
        if not decision_files:
            return [AIActFinding(
                article="Art.22",
                requirement="No automated decisions detected",
                status="present",
                severity="medium",
                evidence="no automated decision patterns found",
                remediation="If automated decisions are added, ensure human override and appeal mechanisms exist.",
            )]
        if override_found:
            return [AIActFinding(
                article="Art.22",
                requirement="Automated decisions have human override",
                status="present",
                severity="medium",
                evidence=decision_files[0],
                remediation="Verify override path is accessible to users, not only operators.",
            )]
        return [AIActFinding(
            article="Art.22",
            requirement="Automated individual decision-making requires human override (Art. 22)",
            status="missing",
            severity="critical",
            evidence=decision_files[0] if decision_files else "not found",
            remediation="Add human_override() and appeal mechanism before any pass/fail decision affecting individuals.",
        )]

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _iter_text_files(self, repo: Path, exts: Optional[set] = None):
        target = exts if exts is not None else _TEXT_EXTS
        for fpath in repo.rglob("*"):
            if not fpath.is_file():
                continue
            if any(part in _SKIP_DIRS for part in fpath.parts):
                continue
            if fpath.suffix.lower() in target:
                yield fpath

    def _conformity_score(self, findings: List[AIActFinding]) -> float:
        if not findings:
            return 1.0
        _weights = {"present": 1.0, "partial": 0.5, "missing": 0.0}
        scores = [_weights.get(f.status, 0.0) for f in findings]
        return round(sum(scores) / len(scores), 4)
