"""
Frontend Test Runner

Executes tests generated by FrontendTestGenerator and normalises the output
into the same result dict that _run_tests() (agent_api.py) produces, so the
pipeline fix-loop works identically regardless of framework.

Result schema (matches agent_api.py _run_tests output)
-------------------------------------------------------
{
    "status":   "ALL_PASSED" | "SOME_FAILED" | "ALL_FAILED" | "ERROR" | "NO_TESTS_COLLECTED",
    "passed":   int,
    "failed":   int,
    "errors":   int,
    "total":    int,
    "pass_rate": float,      # 0.0–1.0
    "tests":    [{"name": str, "status": "PASSED"|"FAILED"|"ERROR", "output": str}],
    "output":   str,         # raw combined stdout/stderr
    "framework": str,
    "runner":   str,
}
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import List, Optional

from agenticqa.testing.frontend_test_generator import (
    Framework,
    FrameworkDetector,
    FrontendTestGenerator,
    GeneratedFrontendTest,
)


# ── Result builder ─────────────────────────────────────────────────────────────

def _make_result(
    passed: int,
    failed: int,
    errors: int,
    tests: list,
    output: str,
    framework: str,
    runner: str,
) -> dict:
    total = passed + failed + errors
    if total == 0:
        status = "NO_TESTS_COLLECTED"
        pass_rate = 0.0
    elif failed == 0 and errors == 0:
        status = "ALL_PASSED"
        pass_rate = 1.0
    elif passed == 0:
        status = "ALL_FAILED"
        pass_rate = 0.0
    else:
        status = "SOME_FAILED"
        pass_rate = passed / total

    return {
        "status": status,
        "passed": passed,
        "failed": failed,
        "errors": errors,
        "total": total,
        "pass_rate": pass_rate,
        "tests": tests,
        "output": output[:8000],
        "framework": framework,
        "runner": runner,
    }


def _error_result(msg: str, framework: str = "unknown", runner: str = "unknown") -> dict:
    return _make_result(0, 0, 1, [{"name": "setup", "status": "ERROR", "output": msg}],
                        msg, framework, runner)


# ── Parsers ────────────────────────────────────────────────────────────────────

def _parse_pytest(output: str) -> dict:
    """Parse pytest stdout into structured results."""
    tests = []
    passed = failed = errors = 0

    # Individual test lines: "PASSED tests/foo.py::test_bar" or "FAILED ..."
    for line in output.splitlines():
        m = re.match(r"(PASSED|FAILED|ERROR)\s+(.+?)(?:\s+-\s+.+)?$", line.strip())
        if m:
            status, name = m.group(1), m.group(2).strip()
            tests.append({"name": name, "status": status, "output": ""})
            if status == "PASSED":
                passed += 1
            elif status == "FAILED":
                failed += 1
            else:
                errors += 1

    # Summary line: "3 passed, 1 failed in 0.12s"
    summary = re.search(
        r"(\d+) passed(?:,\s*(\d+) failed)?(?:,\s*(\d+) error)?", output
    )
    if summary and not tests:
        passed = int(summary.group(1) or 0)
        failed = int(summary.group(2) or 0)
        errors = int(summary.group(3) or 0)
        for i in range(passed):
            tests.append({"name": f"test_{i+1}", "status": "PASSED", "output": ""})
        for i in range(failed):
            tests.append({"name": f"test_fail_{i+1}", "status": "FAILED", "output": ""})

    return {"passed": passed, "failed": failed, "errors": errors, "tests": tests}


def _parse_jest(output: str) -> dict:
    """Parse Jest stdout (plain or --json) into structured results."""
    tests = []
    passed = failed = errors = 0

    # Try JSON output first
    for line in output.splitlines():
        line = line.strip()
        if line.startswith("{") and '"testResults"' in line:
            try:
                data = json.loads(line)
                for suite in data.get("testResults", []):
                    for t in suite.get("testResults", []):
                        name = t.get("fullName", t.get("title", "unnamed"))
                        status_raw = t.get("status", "unknown")
                        st = "PASSED" if status_raw == "passed" else (
                            "FAILED" if status_raw == "failed" else "ERROR"
                        )
                        tests.append({"name": name, "status": st,
                                      "output": "\n".join(t.get("failureMessages", []))})
                        if st == "PASSED":
                            passed += 1
                        elif st == "FAILED":
                            failed += 1
                        else:
                            errors += 1
                return {"passed": passed, "failed": failed, "errors": errors, "tests": tests}
            except Exception:
                pass

    # Plain-text fallback
    for line in output.splitlines():
        m_p = re.search(r"✓|✔|PASS\s+(.+)", line)
        m_f = re.search(r"✗|✘|FAIL\s+(.+)", line)
        if m_p:
            name = m_p.group(1).strip() if m_p.group(1) else line.strip()
            tests.append({"name": name, "status": "PASSED", "output": ""})
            passed += 1
        elif m_f:
            name = m_f.group(1).strip() if m_f.group(1) else line.strip()
            tests.append({"name": name, "status": "FAILED", "output": line})
            failed += 1

    # Summary: "Tests: 3 passed, 1 failed"
    summary = re.search(r"Tests:\s+(?:(\d+) passed)?(?:,\s*(\d+) failed)?", output)
    if summary and not tests:
        passed = int(summary.group(1) or 0)
        failed = int(summary.group(2) or 0)

    return {"passed": passed, "failed": failed, "errors": errors, "tests": tests}


def _parse_vitest(output: str) -> dict:
    """Parse Vitest output (similar to Jest)."""
    return _parse_jest(output)  # output format is compatible


# ── Runner ─────────────────────────────────────────────────────────────────────

class FrontendTestRunner:
    """Run generated tests and return normalised results."""

    def run(
        self,
        description: str,
        code: str,
        file_path: str,
        repo_path: str = ".",
        timeout: int = 60,
    ) -> dict:
        """
        Detect framework, generate tests, write them to disk, run them.

        Returns the normalised result dict.
        """
        detection = FrameworkDetector().detect(repo_path, file_path)
        generated = FrontendTestGenerator().generate(
            description, code, file_path, repo_path, detection
        )
        return self.run_generated(generated, repo_path, timeout=timeout)

    def run_generated(
        self,
        generated: GeneratedFrontendTest,
        repo_path: str = ".",
        timeout: int = 60,
    ) -> dict:
        """Write the generated test file and execute it."""
        root = Path(repo_path)
        test_path = root / generated.test_filename
        test_path.parent.mkdir(parents=True, exist_ok=True)
        test_path.write_text(generated.test_code, encoding="utf-8")

        # Build the base command — use the executable from test_command but
        # strip any flags that we will re-add ourselves to avoid duplication
        # (double -q becomes -qq which suppresses the summary line).
        base_parts = generated.test_command.split()
        # Keep only the interpreter/runner prefix: everything up to the runner binary
        # e.g. ["python", "-m", "pytest"] from "python -m pytest --tb=short -q"
        runner_end = 0
        for i, part in enumerate(base_parts):
            if part in ("pytest", "jest", "vitest", "npx"):
                runner_end = i + 1
                break
        cmd_parts = base_parts[:runner_end] if runner_end else base_parts

        # For pytest-based runners, add the specific test file with explicit flags
        if generated.test_runner == "pytest":
            cmd_parts += [str(test_path), "--tb=short", "-v", "--no-header"]

        try:
            proc = subprocess.run(
                cmd_parts,
                cwd=str(root),
                capture_output=True,
                text=True,
                timeout=timeout,
                env={**os.environ, "CI": "true", "NO_COLOR": "1"},
            )
            output = proc.stdout + "\n" + proc.stderr
        except subprocess.TimeoutExpired:
            return _error_result(
                f"Test run timed out after {timeout}s",
                generated.framework.value,
                generated.test_runner,
            )
        except FileNotFoundError as exc:
            return _error_result(
                f"Test runner not found: {exc}. "
                f"Run: {' '.join(generated.setup_instructions[:1])}",
                generated.framework.value,
                generated.test_runner,
            )
        except Exception as exc:
            return _error_result(str(exc), generated.framework.value, generated.test_runner)

        # Parse output
        if generated.test_runner == "pytest":
            parsed = _parse_pytest(output)
        elif generated.test_runner in ("jest",):
            parsed = _parse_jest(output)
        elif generated.test_runner in ("vitest",):
            parsed = _parse_vitest(output)
        else:
            parsed = _parse_pytest(output)  # best-effort

        return _make_result(
            parsed["passed"],
            parsed["failed"],
            parsed["errors"],
            parsed["tests"],
            output,
            generated.framework.value,
            generated.test_runner,
        )
